# Generated by Django 5.1.5 on 2025-01-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20),
        ),
    ]
